template: 'facelessuser:master-labels:labels.yml:master'

# Wildcard labels

brace_expansion: true
extended_glob: true
minus_negate: false

rules:
  - labels: ['C: infrastructure']
    patterns: ['*|!@(*.md|*.py|*.sublime-@(keymap|menu|settings|commands))', '.github/**']

  - labels: ['C: source']
    patterns: ['st[0-9]/mdpopups/**|**/*.sublime-@(keymap|menu|settings|commands)|!tests']

  - labels: ['C: docs']
    patterns: ['**/*.md|docs/**']

  - labels: ['C: tests']
    patterns: ['tests/**']

  - labels: ['C: code-highlight']
    patterns: ['st[0-9]/mdpopups/mdx/**|st[0-9]/mdpopups/@(st_@(code|pygments)_highlight.py|)']

  - labels: ['C: API']
    patterns: ['st[0-9]/mdpopups/__init__.py']

  - labels: ['C: code-highlight', 'C: languages']
    patterns: ['st[0-9]/mdpopups/st_mapping.py']

  - labels: ['C: scheme-support']
    patterns: ['st[0-9]/mdpopups/st_@(color_scheme_matching|scheme_template).py|css/**']

  - labels: ['C: images']
    patterns: ['st[0-9]/mdpopups/@(png|imagetint|colorbox).py']

  - labels: ['C: colors']
    patterns: ['st[0-9]/mdpopups/@(rgba|x11colors).py']

  - labels: ['C: settings']
    patterns: ['**/*.sublime-@(keymap|menu|settings|commands)']

labels:
- name: 'C: code-highlight'
  renamed: code-highlight
  color: subcategory
  description: Related to code highlighting.

- name: 'C: API'
  renamed: API
  color: subcategory
  description: Related to the API.

- name: 'C: languages'
  renamed: languages
  color: subcategory
  description: Related to supported code lanugage mapping for highlighter.

- name: 'C: scheme-support'
  renamed: scheme-support
  color: subcategory
  description: Related to handling color schemes.

- name: 'C: images'
  renamed: images
  color: subcategory
  description: Related to image processing/creation.

- name: 'C: colors'
  renamed: colors
  color: subcategory
  description: Related to color handling.

- name: 'C: settings'
  renamed: settings
  color: subcategory
  description: Related to Sublime settings files.
